version: '3.1'
services:
  stats-server:
    build: ./ewm-stats-service/server/
    image: stats_server_image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - DB_USER=test
      - DB_PASSWORD=test
      - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "7777:5432"
    volumes:
      - data-stats:/var/lib/postgresql/data
    #     - /var/lib/postgresql@16/data-stats
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./ewm-main-service
    image: ewm_main_service_image
    container_name: ewm_main_service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SERVER_PORT=8080
      #      - TZ=Europe/Moscow
      - DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - EWM_STATS_SERVER_URL=http://stats-server:9090
      - DB_USER=test
      - DB_PASSWORD=test
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "7778:5432"
    volumes:
      - data-ewm:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
volumes:
  data-ewm:
  data-stats:

